apps/session/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.SessionView.as_view(), name='session'),
]

litchi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^session/', include('apps.session.urls', namespace='session')),
]

apps/session/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

logic/db/litchi/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractUser
from django.db import models


class Group(models.Model):
    name = models.CharField('名称', max_length=10, unique=True)
    desc = models.CharField('描述', max_length=50, blank=True, null=True)

    class Meta:
        verbose_name = '用户组'
        verbose_name_plural = verbose_name
        ordering = ['id',]

    def __str__(self):
        return self.name


class Member(AbstractUser):
    ROLE_CHOICES = (
        ('Admin', '管理员'),
        ('User', '普通用户'),
    )
    role = models.CharField('角色', max_length=5, choices=ROLE_CHOICES, default='User')
    email = models.EmailField('邮箱', unique=True)
    group = models.ManyToManyField(Group, verbose_name='用户组')
    avatar = models.ImageField('头像', upload_to='avatar/%Y/%m/%d', blank=True, null=True)
    rsakey = models.CharField('私钥', max_length=5000)

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['id',]

    def __str__(self):
        return self.username

apps/session/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from captcha.fields import CaptchaField


class SessionLoginForm(forms.Form):
    username = forms.EmailField(
        required=True,
        error_messages={
            'invalid': '邮箱格式错误',
            'required': '用户名不能为空',
        },
    )
    password = forms.CharField(
        required=True,
        error_messages={
            'required': '密码不能为空',
        },
    )
    captcha = CaptchaField(
        required=True,
        error_messages = {
            'invalid': '验证码错误',
            'required': '验证码不能为空',
        },
    )

app/session/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from captcha.helpers import captcha_image_url
from captcha.models import CaptchaStore

from utils.decorators import nonlogin_required
from .forms import SessionLoginForm


class SessionView(View):

    @method_decorator(nonlogin_required)
    def get(self, request):
        captcha_key = CaptchaStore.generate_key()
        captcha_url = captcha_image_url(captcha_key)
        context = {
            'captcha_key': captcha_key,
            'captcha_url': captcha_url,
        }
        return render(request, 'login.html', context)

    @method_decorator(nonlogin_required)
    def post(self, request):
        data = json.loads(request.body)
        form = SessionLoginForm(data)
        captcha_key = CaptchaStore.generate_key()
        captcha_url = captcha_image_url(captcha_key)
        if form.is_valid():
            data = form.cleaned_data
            username = data.get('username')
            password = data.get('password')
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                error_msg = '用户名或密码错误'
                context = {
                    'error_msg': error_msg,
                    'captcha_key': captcha_key,
                    'captcha_url': captcha_url,
                }
                return render(request, 'login.html', context)
        else:
            context = {
                'form': form,
                'captcha_key': captcha_key,
                'captcha_url': captcha_url,
            }
            return render(request, 'login.html', context)

    @method_decorator(login_required(redirect_field_name=None, login_url='/session/'))
    def delete(self, request):
        logout(request)
        return HttpResponseRedirect('/')

apps/session/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from captcha.helpers import captcha_image_url
from captcha.models import CaptchaStore

from logic.ext_django.response import JsonResponseRedirect
from logic.utils.decorators import nonlogin_required
from .forms import SessionLoginForm


class SessionView(View):

    #@method_decorator(nonlogin_required)
    def get(self, request):
        captcha_key = CaptchaStore.generate_key()
        captcha_url = captcha_image_url(captcha_key)
        context = {
            'captcha_key': captcha_key,
            'captcha_url': captcha_url,
        }
        return render(request, 'login.html', context)

    #@method_decorator(nonlogin_required)
    def put(self, request):
        data = json.loads(request.body)
        form = SessionLoginForm(data)
        captcha_key = CaptchaStore.generate_key()
        captcha_url = captcha_image_url(captcha_key)
        if form.is_valid():
            data = form.cleaned_data
            username = data.get('username')
            password = data.get('password')
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return JsonResponseRedirect('/')
            else:
                error_msg = '用户名或密码错误'
                context = {
                    'error_msg': error_msg,
                    'captcha_key': captcha_key,
                    'captcha_url': captcha_url,
                }
                return render(request, 'login.html', context)
        else:
            context = {
                'form': form,
                'captcha_key': captcha_key,
                'captcha_url': captcha_url,
            }
            return render(request, 'login.html', context)

    @method_decorator(login_required(redirect_field_name=None, login_url='/session/'))
    def delete(self, request):
        logout(request)
        return JsonResponseRedirect('/')

apps/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

logic/db/litchi/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

apps/session/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>宝宝云</title>
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
  <link rel="stylesheet" href="{% static "css/reset.css" %}">
  <link rel="stylesheet" href="{% static "css/style.css" %}">
  <link rel="stylesheet" href="{% static "css/login.css" %}">
  <script src="{% static "js/jquery.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  <script src="{% static "js/login.js" %}"></script>
</head>
<body>
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">宝宝云</a>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav navbar-left">
            <li><a href="#">最新活动</a></li>
            <li><a href="#">产品服务</a></li>
            <li><a href="#">技术支持</a></li>
            <li><a href="#">客户案例</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">控制台</a></li>
            <li class="hidden-xs vertical-line">|</li>
            <li><a href="{% url "session:session" %}">登录</a></li>
            <li><a href="#">注册</a></li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <div class="main">
    <div class="center-block signin">
      <form id="loginForm" action="{% url "session:session" %}" method="put">
        {{ error_msg }}
        <div class="form-group">
          <input class="form-control input-lg" name="username" type="text" placeholder="注册邮箱">
        </div>
        <div class="form-group">
          <div class="input-group">
            <input class="form-control input-lg" name="password" type="password" placeholder="登录密码">
            <span class="input-group-addon"><a href="#">忘记密码?</a></span>
          </div>
        </div>
        <div class="form-group">
          <div class="input-group">
            <input class="form-control input-lg" name="captcha_1" type="text" placeholder="验证码">
            <span class="input-group-addon"><img id="captchaRefresh" class="captcha" src="{{ captcha_url }}"></span>
          </div>
        </div>
        <div class="form-group">
          <input name="captcha_0" type="hidden" value="{{ captcha_key }}">
          {% csrf_token %}
        </div>
        <div class="form-group">
          <input id="loginBtn" class="form-control input-lg btn-primary" type="button" value="立即登录">
        </div>
      </form>
    </div>
    <div class="center-block signin-third">
      <div class="signin-third-title">
        <i></i><span>第三方登录</span><i></i>
      </div>
      <div class="signin-third-body">
        <div class="container-fluid ">
          <div class="row">
            <div class="col-md-4 col-xs-4 text-center">
              <a class="icon icon-qq" href="#"></a>
            </div>
            <div class="col-md-4 col-xs-4 text-center">
              <a class="icon icon-wechat" href="#"></a>
            </div>
            <div class="col-md-4 col-xs-4 text-center">
              <a class="icon icon-github" href="#"></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <footer>
    <div class="copyright">
      &copy;&nbsp;2017&nbsp;宝宝云&nbsp;版权所有
    </div>
  </footer>
</body>
</html>